### ISSUE TITLE
Encountered an error while trying to add backward compatibility  for XE4

### ISSUE THREAD

**Issue by edwinyzh** [marat1961/Oz-SGL#8]
Hello,

I'm glad to have found this interesting project! I'm trying make some changes to the repository so that it compiles under XE4. I've done several as you can see in the PR #7 ,  but not sure what to do for the compiler error as you can see in the attached screenshot :) Any help?

![2020-10-09_15h03_32](https://user-images.githubusercontent.com/541197/95553213-a78aac80-0a40-11eb-94f5-0ebe6549c916.png)

**Comment by marat1961** [comment]
Hi

I am currently using delphi 10.3 community edition.
Unfortunately, this is the only version of Delphi available to me.

If it's critical for you I can see how it can be implemented in delphi xe4. But since then a lot of water in the rivers has gone away.

I would be most interested in trying to compile projects for Free Pascal.

I used to work on Pascal for PDP-11, Turbo-pascal, JPI Pascal. But I never got to FP, and there were no tasks for this language implementation.

Translated with www.DeepL.com/Translator (free version)

**Comment by edwinyzh** [comment]
A discussions of your library on the Praxis Delphi forum that might can be of your information: https://en.delphipraxis.net/topic/3648-oz-sgl-a-new-generic-collections-library-based-on-the-idea-of-c-stl/?tab=comments#comment-30755

**Comment by marat1961** [comment]
fixed
